# Numpy practice

In [3]:
import numpy as np

In [2]:
myarr = np.array([5,75,63])

In [3]:
myarr

array([ 5, 75, 63])

In [4]:
a = np.array([1,2,3], dtype = 'int32')
print(a)

[1 2 3]


In [4]:
b = np.array([[9,5,3],[6,2,6]])
print(b)

[[9 5 3]
 [6 2 6]]


In [6]:
# Get Dimensions
b.ndim

2

In [7]:
# Get Shape
b.shape

(2, 3)

In [8]:
# get Type
a.dtype

dtype('int32')

In [5]:
# Get Size 
b.itemsize

8

In [10]:
myarr = np.array([[4,32,44,5]],np.int64)

In [11]:
myarr

array([[ 4, 32, 44,  5]])

In [12]:
myarr[0,3]

np.int64(5)

In [13]:
myarr.shape

(1, 4)

In [14]:
myarr.dtype

dtype('int64')

In [15]:
 myarr[0,2]= 55

In [16]:
myarr

array([[ 4, 32, 55,  5]])

# Array creation: conversion from other python structure

In [17]:
listarray = np.array([[1,1,2],[6,5,8],[87,5,334]])

In [18]:
listarray

array([[  1,   1,   2],
       [  6,   5,   8],
       [ 87,   5, 334]])

In [19]:
listarray.dtype

dtype('int64')

In [20]:
listarray.shape

(3, 3)

In [21]:
listarray.size

9

In [22]:
np.array({33,65,64})

array({64, 65, 33}, dtype=object)

In [23]:
zeros = np.zeros((2,6))

In [24]:
zeros

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [25]:
#zeros.dtype
zeros.size
#zeros.shape

12

In [26]:
print(np.arange(15))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [27]:
linspace = np.linspace(1,5,12)  # 1-5 ke bich equally spaced 12 elements dega

In [28]:
linspace

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [29]:
emp = np.empty((4,6))

In [30]:
emp

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        1.37962796e-306, 2.00262080e-307, 7.56603202e-307],
       [1.42413555e-306, 1.78019082e-306, 1.37960147e-306,
        1.33511562e-306, 2.22518251e-306, 1.33511969e-306],
       [1.78022342e-306, 1.05700345e-307, 1.69118108e-306,
        8.06632139e-308, 1.20160711e-306, 1.69119330e-306],
       [1.29062229e-306, 6.89804133e-307, 1.11261298e-306,
        6.89804132e-307, 1.11261162e-306, 8.34443015e-308]])

In [31]:
emp_like = np.empty_like(linspace) 

In [32]:
emp_like

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [33]:
ide = np.identity(45)

In [34]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]], shape=(45, 45))

In [6]:
array = np.arange(50)

In [7]:
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [8]:
 array = array.reshape(5,10) #multipl.. should be eql to previous array

In [9]:
array

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [39]:
array = array.ravel()

In [40]:
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [41]:
array.shape

(50,)

**Numpy Axis**

In [42]:
x = [[1,2,3],[4,5,6],[7,1,0]]

In [43]:
arr = np.array(x)

In [44]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [45]:
arr.sum(axis = 0)

array([12,  8,  9])

In [46]:
arr.sum(axis = 1)

array([ 6, 15,  8])

In [47]:
 arr.T     # transpose the array

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [48]:
arr.flat

In [49]:
for item in arr.flat:
    print(item)

1
2
3
4
5
6
7
1
0


In [50]:
arr.ndim

2

In [51]:
arr.size

9

In [52]:
arr.shape

(3, 3)

In [53]:
arr.nbytes

72

In [54]:
one = np.array([1,6,99,87])

In [55]:
one

array([ 1,  6, 99, 87])

In [56]:
one.ndim

1

In [57]:
one.sum(axis = 0)

np.int64(193)

In [58]:
one.argmax()   #gives index of max element 

np.int64(2)

In [59]:
one.argmin()   #gives index of min element

np.int64(0)

In [60]:
one.argsort()   # give the indexes to sort array

array([0, 1, 3, 2])

In [61]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [62]:
arr.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]])

In [63]:
arr.argmin()   #gives index of min element after flattening it

np.int64(8)

In [64]:
arr.argmax()

np.int64(6)

In [65]:
arr.argmax(axis = 0)

array([2, 1, 1])

In [66]:
arr.argmax(axis = 1)

array([2, 2, 0])

In [67]:
arr.argsort(axis = 1)

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]])

In [68]:
arr.argsort(axis = 0)

array([[0, 2, 2],
       [1, 0, 0],
       [2, 1, 1]])

In [69]:
arr.ravel()

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [70]:
arr.reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [71]:
arr2 = np.array([[1, 2, 1],
       [4, 0, 6],
       [8, 1, 0]])

In [72]:
arr2

array([[1, 2, 1],
       [4, 0, 6],
       [8, 1, 0]])

In [73]:
arr + arr2

array([[ 2,  4,  4],
       [ 8,  5, 12],
       [15,  2,  0]])

In [74]:
arr * arr2

array([[ 1,  4,  3],
       [16,  0, 36],
       [56,  1,  0]])

In [75]:
arr - arr2

array([[ 0,  0,  2],
       [ 0,  5,  0],
       [-1,  0,  0]])

In [76]:
np.sqrt(arr+arr2)

array([[1.41421356, 2.        , 2.        ],
       [2.82842712, 2.23606798, 3.46410162],
       [3.87298335, 1.41421356, 0.        ]])

In [77]:
arr.sum()

np.int64(29)

In [78]:
arr.max()

np.int64(7)

In [79]:
arr.min()

np.int64(0)

In [80]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [81]:
np.where(arr>5)

(array([1, 2]), array([2, 0]))

In [82]:
type(np.where(arr>5))

tuple

In [83]:
np.count_nonzero(arr)

8

In [84]:
np.nonzero(arr)

(array([0, 0, 0, 1, 1, 1, 2, 2]), array([0, 1, 2, 0, 1, 2, 0, 1]))

In [85]:
arr[1,2] = 0

In [86]:
np.nonzero(arr)

(array([0, 0, 0, 1, 1, 2, 2]), array([0, 1, 2, 0, 1, 0, 1]))

In [87]:
import sys

In [88]:
py_ar = [0,4,55,2]

In [89]:
np_ar = np.array(py_ar)

In [90]:
sys.getsizeof(1) * len(py_ar)

112

In [91]:
np_ar.itemsize * np_ar.size

32

In [92]:
np_ar.tolist()

[0, 4, 55, 2]

In [95]:
arr2.T

array([[1, 4, 8],
       [2, 0, 1],
       [1, 6, 0]])